"""Adicionar campos foto aos modelos Usuario e Dossie

Revision ID: ec4101429d0a
Revises: c6d863870b87
Create Date: 2025-06-10 18:31:53.990783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec4101429d0a'
down_revision = 'c6d863870b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('dossies', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
