"""Initial migration

Revision ID: initial_migration
Revises: 
Create Date: 2025-06-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('descricao', sa.String(length=200), nullable=True),
        sa.Column('nivel', sa.Integer(), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )

    op.create_table('permissoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=50), nullable=False),
        sa.Column('descricao', sa.String(length=200), nullable=True),
        sa.Column('modulo', sa.String(length=50), nullable=False),
        sa.Column('acao', sa.String(length=50), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nome')
    )

    op.create_table('perfil_permissoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('perfil_id', sa.Integer(), nullable=False),
        sa.Column('permissao_id', sa.Integer(), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
        sa.ForeignKeyConstraint(['permissao_id'], ['permissoes.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('cidades',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('uf', sa.String(length=2), nullable=False),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('escolas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('cnpj', sa.String(length=18), nullable=True),
        sa.Column('endereco', sa.String(length=200), nullable=True),
        sa.Column('cidade_id', sa.Integer(), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['cidade_id'], ['cidades.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cnpj')
    )

    op.create_table('usuarios',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('foto', sa.String(length=200), nullable=True),
        sa.Column('escola_id', sa.Integer(), nullable=True),
        sa.Column('perfil_id', sa.Integer(), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
        sa.Column('data_nascimento', sa.Date(), nullable=True),
        sa.Column('data_registro', sa.DateTime(), nullable=True),
        sa.Column('senha_hash', sa.String(length=200), nullable=False),
        sa.Column('tentativas_login', sa.Integer(), nullable=True),
        sa.Column('bloqueado_ate', sa.DateTime(), nullable=True),
        sa.Column('data_alteracao_senha', sa.DateTime(), nullable=True),
        sa.Column('senha_expira_em', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('data_cadastro', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
        sa.ForeignKeyConstraint(['perfil_id'], ['perfis.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf'),
        sa.UniqueConstraint('email')
    )

    op.create_table('diretores',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('foto', sa.String(length=200), nullable=True),
        sa.Column('escola_id', sa.Integer(), nullable=True),
        sa.Column('data_inicio', sa.Date(), nullable=True),
        sa.Column('data_fim', sa.Date(), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf')
    )

    op.create_table('dossies',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('numero', sa.String(length=20), nullable=False),
        sa.Column('escola_id', sa.Integer(), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('numero')
    )

    op.create_table('movimentacoes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('dossie_id', sa.Integer(), nullable=True),
        sa.Column('tipo', sa.String(length=20), nullable=False),
        sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('data_conclusao', sa.DateTime(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['dossie_id'], ['dossies.id'], ),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('anexos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=200), nullable=False),
        sa.Column('tipo', sa.String(length=50), nullable=True),
        sa.Column('tamanho', sa.Integer(), nullable=True),
        sa.Column('caminho', sa.String(length=200), nullable=False),
        sa.Column('dossie_id', sa.Integer(), nullable=True),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('data_upload', sa.DateTime(), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['dossie_id'], ['dossies.id'], ),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('solicitantes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nome', sa.String(length=100), nullable=False),
        sa.Column('cpf', sa.String(length=14), nullable=True),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('telefone', sa.String(length=20), nullable=True),
        sa.Column('escola_id', sa.Integer(), nullable=True),
        sa.Column('situacao', sa.String(length=20), nullable=True),
        sa.Column('data_criacao', sa.DateTime(), nullable=True),
        sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cpf')
    )

    op.create_table('log_auditoria',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('acao', sa.String(length=50), nullable=False),
        sa.Column('data_hora', sa.DateTime(), nullable=True),
        sa.Column('item_alterado', sa.String(length=100), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('navegador', sa.String(length=200), nullable=True),
        sa.Column('detalhes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('log_sistema',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('mensagem_erro', sa.Text(), nullable=False),
        sa.Column('usuario_id', sa.Integer(), nullable=True),
        sa.Column('nivel_erro', sa.String(length=20), nullable=True),
        sa.Column('data_hora', sa.DateTime(), nullable=True),
        sa.Column('modulo', sa.String(length=50), nullable=True),
        sa.Column('funcao', sa.String(length=100), nullable=True),
        sa.Column('linha', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_sistema')
    op.drop_table('log_auditoria')
    op.drop_table('solicitantes')
    op.drop_table('anexos')
    op.drop_table('movimentacoes')
    op.drop_table('dossies')
    op.drop_table('diretores')
    op.drop_table('usuarios')
    op.drop_table('escolas')
    op.drop_table('cidades')
    op.drop_table('perfil_permissoes')
    op.drop_table('permissoes')
    op.drop_table('perfis')
    # ### end Alembic commands ### 